app/urls.py
from .views import index, CategoryView, CategoryDetailView, IndexView, UserDetailView
from django.urls import path



app_name = "app"
urlpatterns = [
    path("", IndexView.as_view(), name='index'),
    path("i/<int:id>", CategoryView.as_view(), name='post'),
    path("i/<int:category_id>/<int:id>", CategoryDetailView.as_view(), name='detail'),
    path("user/<str:category_id>/<str:id>", UserDetailView.as_view(), name='user'),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static, re_path
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
# from app.views import index

urlpatterns = [
    path(_('admin/'), admin.site.urls),
    path('', include("app.urls")),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += i18n_patterns(
        path('', include("app.urls"))
)
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

document/models.py
from django.db import models
from ckeditor.fields import RichTextField


class ArticleCategory(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return str(self.name)
    
class Article(models.Model):
    category = models.ForeignKey(ArticleCategory, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=400, null=True, blank=True)
    description = RichTextField()
    views = models.IntegerField(default=0)

    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)
    
class ArticleImage(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='article/', null=True, blank=True)
    
    def __str__(self):
        return str(self.article)
    

templates/_base.html
{% load compress %}
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% trans 'SIRDARYO-ZARAFSHON Irrigatsiya tizimlari havza boshqarmasi' %}</title>

    <link rel="icon" type="image/x-icon" href="{% static 'favicon.png' %}">

    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress %}

</head>

<body class="bg-midnight text-tahiti">

{% include 'head-banner.html' %}

<header class="sticky top-0 z-50">
    {% include 'header.html' %}
</header>
<div class=" md:mx-auto m-5">
<!-- <div class="md:max-w-2xl"> -->
    <div class="md:flex">
    <div class="md:shrink-0 md:ml-20">
        {% include 'sidebar.html' %}

    </div>
    <div class="w-full ">
    {% block content %}
    {% endblock %}
</div>
</div>
</div>


{% include 'footer.html' %}
<script>
    const submenus = document.querySelectorAll('.submenu');
    submenus.forEach((submenu) => {
        submenu.addEventListener('toggle', (event) => {
            if (event.target.open) {
                closeOtherSubmenus(submenu);
            }
        });
    });

    function closeOtherSubmenus(openSubmenu) {
        submenus.forEach((submenu) => {
            if (submenu !== openSubmenu) {
                submenu.removeAttribute('open');
            }
        });
    }
</script>
<link href="/static/src/flowbite.min.css" rel="stylesheet" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
</body>

</html>

templates/article_detail.html
{% extends "_base.html" %}
{% load static %}
{% block content %}

<section>
   
    <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16">
        <div> 
            <p>
                 {% if category_id %}
        
                  
                 <a href="{% url 'app:post' category_id %}">🔙 Ortga qaytish</a>
                 {% endif %}
            </p>
        </div>
        <div class="border glass bg-gray-50 rounded-lg p-8 md:p-12 mb-8">
            <h6 class="mb-2 text-3l tracking-tight text-gray-900 "><div class="flex">{{article.date|date:"d M Y"}} | &nbsp;<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M15.1614 12.0531C15.1614 13.7991 13.7454 15.2141 11.9994 15.2141C10.2534 15.2141 8.83838 13.7991 8.83838 12.0531C8.83838 10.3061 10.2534 8.89111 11.9994 8.89111C13.7454 8.89111 15.1614 10.3061 15.1614 12.0531Z" stroke="#200E32" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                <path fill-rule="evenodd" clip-rule="evenodd" d="M11.998 19.3549C15.806 19.3549 19.289 16.6169 21.25 12.0529C19.289 7.48885 15.806 4.75085 11.998 4.75085H12.002C8.194 4.75085 4.711 7.48885 2.75 12.0529C4.711 16.6169 8.194 19.3549 12.002 19.3549H11.998Z" stroke="#200E32" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
                {{article.views}}</div></h6>
                <br>

            <h1 class="text-gray-900xl font-extrabold mb-2">{{article.title}}</h1>
         
<br>
            <div id="default-carousel" class="relative w-full" data-carousel="slide">
                <!-- Carousel wrapper -->
                <div class="relative h-56 overflow-hidden rounded-lg md:h-96">
                  {% for img in article.articleimage_set.all %}
                  
                  <!-- <img src="{{ img.image.url }}"> -->
                  {% if img == article.articleimage_set.all.first %}
                  <div class="duration-700 ease-in-out active" data-carousel-item>
                    <img src="{{img.image.url}}" class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
                  </div>
            
                  {% else %}
                  <div class="duration-700 ease-in-out " data-carousel-item>
                    <img src="{{ img.image.url }}" class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
                  </div>
                  {% endif %}
                  {% endfor %}
              
                    
                </div>
                <!-- Slider indicators -->
                <div class="absolute z-30 flex space-x-3 -translate-x-1/2 bottom-5 left-1/2">
                  {% for img in article.articleimage_set.all %}
                  <button type="button" class="w-3 h-3 rounded-full" aria-current="true" aria-label="Slide 1" data-carousel-slide-to="{{ img.id }}"></button>
            
                  {% endfor %}
                </div>
                <!-- Slider controls -->
                <button type="button" class="absolute top-0 left-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-prev>
                    <span class="inline-flex items-center justify-center w-8 h-8 rounded-full sm:w-10 sm:h-10 bg-white/30 group-hover:bg-white/50 group-focus:ring-4 group-focus:ring-white group-focus:outline-none">
                        <svg aria-hidden="true" class="w-5 h-5 text-white sm:w-6 sm:h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path></svg>
                        <span class="sr-only">Previous</span>
                    </span>
                </button>
                <button type="button" class="absolute top-0 right-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-next>
                    <span class="inline-flex items-center justify-center w-8 h-8 rounded-full sm:w-10 sm:h-10 bg-white/30 group-hover:bg-white/50 group-focus:ring-4 group-focus:ring-white group-focus:outline-none">
                        <svg aria-hidden="true" class="w-5 h-5 text-white sm:w-6 sm:h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg>
                        <span class="sr-only">Next</span>
                    </span>
                </button>
            </div>

            


            <p class="text-lg font-normal text-gray-500 mb-6">{{article.description| safe}}</p>
            
            {% if request.user == article.author %}

            <a href="#" class="inline-flex justify-center items-center py-2.5 px-5 text-base font-medium text-center text-white rounded-lg bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300">
                Maqolani o'zgartirish
                <svg aria-hidden="true" class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd">
                    </path>
                </svg>
            </a>
            {%endif%}
        </div>

<h1 class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl md-6">Shunga <span class="underline underline-offset-3 decoration-8 decoration-blue-400">aloqador</span></h1>
<div class="flex" onmouseout="scrolview(false)">

<div id="mainscroll" class="static  carousel carousel-center   space-x-4 bg-neutral rounded-box overflow-x-scroll pr-32 pb-4 pt-4 pl-4" onmouseover="scrolview(true)" >
        {% for i in article.category.article_set.all %}
        {% if article != i %}
        <div class="carousel-item object-cover rounded-t-lg md:rounded-none md:rounded-l-lg hover:scroll-auto ">
            <figure class="transition-all duration-300 cursor-pointer filter grayscale hover:grayscale-0">
                <a href="{% url 'app:detail' category_id=i.category.id id=i.id %}">
                    <img src="{{i.articleimage_set.all.first.image.url}}" class="rounded-box object-cover h-96 w-72 " />
                
                <figcaption class="absolute px-4 bottom-6">
                    <p class="text-1xl font-extrabold text-white drop-shadow-lg" style="text-shadow: 1px 2px rgba(0, 0, 0, 0.3);">{{ i.title }}</p>
                </figcaption>
            </a>
              </figure>
            
          </div>
  
        <!-- <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 14rem;">
            <img height="190" class=" card-img-top" src="{{i.articleimage_set.all.first.image.url}}" alt="">
            <div class="card-body">
                <h6 class="align-center card-title"> {{i.title}}</h6>
                <span class="center card-text">${{i.description| safe  | slice:"80"}}</span>
                <div class="buttons d-flex flex-wrap justify-content-between ">
                    <i class="bi bi-bookmark-fill"></i>
                    <a href="{% url 'app:detail' category_id=i.category.id id=i.id %}" class="btn btn-outline-primary">Details</a> -->
        {% endif %}
        {% endfor %}

      </div>
      <!-- style="margin-left: 2rem; margin-top: 11.5rem;" -->
      <button id="leftscroll"  class="md:mt-44 md:ml-8 absolute text-blue-700 border bg-blue-700 hover:border-blue-700 text-white hover:text-gray-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center" onmouseover="scrolview(true)">
        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" style="transform: rotate(180deg);">
            <path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
    
            
        </button>
        <!-- style="margin-left: 74rem; margin-top: 11.5rem;" -->
      <button id="rightscroll"  class="md:mt-44 md:ml-74 absolute text-blue-700 border bg-blue-700 hover:border-blue-700 text-white hover:text-gray-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-full text-sm p-2.5 text-center inline-flex items-center" onmouseover="scrolview(true)">
        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>

    </div>
</div>

</section>
<script>
        const rightscroll = document.getElementById("rightscroll");
    const leftscroll = document.getElementById("leftscroll");
    const mainscroll = document.getElementById('mainscroll');
    rightscroll.onclick = () => {
        mainscroll.scrollLeft += 200;
    };
    leftscroll.onclick = () => {
        mainscroll.scrollLeft -= 200;
    };   
    function scrolview(condition) {
    // Sayt o'zgarishlari
    if (condition) 
    {
        rightscroll.style.display='';
        leftscroll.style.display='';
    } else {
    rightscroll.style.display='none';
    leftscroll.style.display='none';
            }

    }
</script>
{% endblock content %}

templates/article_list.html
{% extends "_base.html" %}
{% load static %}

{% block content %}
<h1 class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white md-6"> <span class="underline underline-offset-3 decoration-8 decoration-blue-400 dark:decoration-blue-600">{{ article }}</span></h1>

<section class="flex flex-wrap  bg-900 text-dark-200 w-full">
            {% for i in articles %}

                <article class="bg-white rounded-lg overflow-hidden shadow-md w-96 m-3">
                   
                        <div class="relative  overflow-hidden">
                            <img class="object-cover w-96 h-48 transform hover:scale-105 transition duration-700 ease-out" src="{{ i.articleimage_set.all.first.image.url }}" alt="Blog post">
                        </div>
                   
                    <div class="p-4">
                        <div>
                            <div class="mb-3">
                                <ul class="flex flex-wrap text-xs font-medium -m-1">
                                    <li class="m-1">
                                        <a class="inline-flex text-center text-gray-100 py-1 px-3 rounded-full bg-blue-500 hover:bg-blue-600 transition duration-150 ease-in-out" href="#0">{{ article }}</a>
                                    </li>
                                </ul>
                            </div>
                            <h3 class="text-xl font-bold leading-tight mb-2">
                                <a class="hover:text-blue-800 transition duration-150 ease-in-out" href="{% url 'app:detail' category_id=i.category.id id=i.id %}">{{i.title}}.</a>
                            </h3>
                        </div>
                        <div class="line-clamp-3 text-gray-400">{{ i.description|safe|escape}}</div>
                        <div class="flex items-center mt-4">
                            <h6 class="mb-2 text-3l tracking-tight text-gray-900 dark:text-white"><div class="flex">{{i.date|date:"d M Y"}} | &nbsp;<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M15.1614 12.0531C15.1614 13.7991 13.7454 15.2141 11.9994 15.2141C10.2534 15.2141 8.83838 13.7991 8.83838 12.0531C8.83838 10.3061 10.2534 8.89111 11.9994 8.89111C13.7454 8.89111 15.1614 10.3061 15.1614 12.0531Z" stroke="#200E32" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M11.998 19.3549C15.806 19.3549 19.289 16.6169 21.25 12.0529C19.289 7.48885 15.806 4.75085 11.998 4.75085H12.002C8.194 4.75085 4.711 7.48885 2.75 12.0529C4.711 16.6169 8.194 19.3549 12.002 19.3549H11.998Z" stroke="#200E32" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                                </svg>
                                {{i.views}}</div></h6>
                            </div>
                        <a href="{% url 'app:detail' category_id=i.category.id id=i.id %}" class="btn btn-outline-primary">Batafsil o'qish</a>
                      </div>
                </article>
            {% endfor %}
        
</section>



{% endblock content %}

templates/documents_list.html
{% extends "_base.html" %}
{% load static %}

{% block content %}

<h2 class="mb-4 text-2xl font-extrabold leading-none tracking-tight text-gray-900 md:text-4xl lg:text-4xl dark:text-white md-6 text-center"> <span class="underline underline-offset-3 decoration-8 decoration-blue-400 dark:decoration-blue-400">{{ article }}</span></h2>

{% for i in articles %}

<div class="justify-center mb-10">

   <div
       class="relative flex flex-col md:flex-row  space-y-3 md:space-y-0 rounded-xl shadow-lg p-3  md:max-w-3xl  border-white bg-white">
       
           <div class="w-full md:w-2/3 bg-white flex flex-col space-y-2 p-3">
               <div class="flex justify-between item-center">
                   
               </div>
               <h3 class="font-black text-gray-800 md:text-3xl text-xl">{{ i.title }}</h3>
               <p class="md:text-lg text-gray-500 text-base">{{ i.subtitle |safe |slice:"200" }}</p>
               <a href="{% url 'app:detail' category_id=i.category.id id=i.id %}" >

               <p class="text-xl font-black text-gray-800  text-center text-link">
                  
                   <span class="font-normal text-gray-600 text-base  ">    Batafsil o'qish...</span>
               </p>
            </a>
           </div>
       </div>

   </div>
   {% endfor %}







{% endblock content %}

templates/index.html
{% extends "_base.html" %}

{% block content %}
<div>
<div id="default-carousel" class="relative w-full" data-carousel="slide">
    <!-- Carousel wrapper -->
    <div class="relative h-56 overflow-hidden rounded-lg md:h-96">
      <a href="{% url 'app:detail' category_id=article.category.id id=article.id %}">
      {% for img in article.articleimage_set.all %}
      
      <!-- <img src="{{ img.image.url }}"> -->

      {% if img == article.articleimage_set.all.first %}
      <div class="hidden duration-700 ease-in-out active" data-carousel-item>
        <img src="{{img.image.url}}" class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
      </div>

      {% else %}
      <div class="hidden duration-700 ease-in-out " data-carousel-item>
        <img src="{{ img.image.url }}" class="absolute block w-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="...">
      </div>
      {% endif %}
      {% endfor %}
    </a>
        
    </div>
    <!-- Slider indicators -->
    <div class="absolute z-30 flex space-x-3 -translate-x-1/2 bottom-5 left-1/2">
      {% for img in article.articleimage_set.all %}
      <button type="button" class="w-3 h-3 rounded-full" aria-current="true" aria-label="Slide 1" data-carousel-slide-to="{{ img.id }}"></button>

      {% endfor %}
    </div>
    <!-- Slider controls -->
    <button type="button" class="absolute top-0 left-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-prev>
        <span class="inline-flex items-center justify-center w-8 h-8 rounded-full sm:w-10 sm:h-10 bg-white/30 group-hover:bg-white/50 group-focus:ring-4 group-focus:ring-white group-focus:outline-none">
            <svg aria-hidden="true" class="w-5 h-5 text-white sm:w-6 sm:h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path></svg>
            <span class="sr-only">Previous</span>
        </span>
    </button>
    <button type="button" class="absolute top-0 right-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-next>
        <span class="inline-flex items-center justify-center w-8 h-8 rounded-full sm:w-10 sm:h-10 bg-white/30 group-hover:bg-white/50 group-focus:ring-4 group-focus:ring-white group-focus:outline-none">
            <svg aria-hidden="true" class="w-5 h-5 text-white sm:w-6 sm:h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg>
            <span class="sr-only">Next</span>
        </span>
    </button>
</div>


<div class="grid grid-flow-row auto-rows-max bg-base-200 mt-6 rounded-box p-6">

    <h1 class="mb-4 text-3xl font-extrabold text-gray-900 md:text-5xl lg:text-6xl"><span class="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">So'nggi</span> Yangiliklar</h1>
    <p class="text-lg font-normal text-gray-500 lg:text-xl ">SIRDARYO-ZARAFSHON
      Irrigatsiya tizimlari havza boshqarmasidagi so'nggi yangiliklari</p>
    
    {% for i in articles %}

    <a href="{% url 'app:detail' category_id=i.category.id id=i.id %}" class="lg:flex bg-white border border-gray-200 rounded-lg shadow md:flex-row mt-2 hover:bg-gray-200">
        <img class="md:h-auto md:max-w-md rounded-lg" src="{{ i.articleimage_set.all.first.image.url }}" alt="">
        <div class="flex flex-col justify-between p-4 leading-normal">
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">{{i.title}}</h5>
            <h6 class="mb-2 text-3l tracking-tight text-gray-900"><div class="flex">{{i.date|date:"d M Y"}} | &nbsp;<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M15.1614 12.0531C15.1614 13.7991 13.7454 15.2141 11.9994 15.2141C10.2534 15.2141 8.83838 13.7991 8.83838 12.0531C8.83838 10.3061 10.2534 8.89111 11.9994 8.89111C13.7454 8.89111 15.1614 10.3061 15.1614 12.0531Z" stroke="#200E32" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                <path fill-rule="evenodd" clip-rule="evenodd" d="M11.998 19.3549C15.806 19.3549 19.289 16.6169 21.25 12.0529C19.289 7.48885 15.806 4.75085 11.998 4.75085H12.002C8.194 4.75085 4.711 7.48885 2.75 12.0529C4.711 16.6169 8.194 19.3549 12.002 19.3549H11.998Z" stroke="#200E32" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
                {{i.views}}</div></h6>
                <div class="line-clamp-3">
                    {{i.description|safe}}
                  </div>
          </div>
    </a>
    
      {%endfor%}
    </div>
    <a href="{% url 'app:post' article.category.id %}">
    <p class="text-lg font-normal text-gray-500 lg:text-xl text-right">Ko'proq yangiliklarni ko'rish ...</p>
  </a>
  </div>
{% endblock content %}

templates/one_page_detail.html
{% extends "_base.html" %}
{% load static %}

{% block content %}

<div class="m-4 mx-5 " style="text-align: justify; margin-right:100px; margin-left:100px">
    <div> 
        <p>
             {% if category_id %}
    
              
             <a href="{% url 'app:post' category_id %}">🔙 Ortga qaytish</a>
             {% endif %}
        </p>
    </div>
<strong>
    <h4 style="text-align:center; font-size: 24px" >{{article.title}}</h4>
</strong>
<br>
<hr>
<br>
    
    <p class="" >{{article.description| safe}}</p>
  
<br>
<hr>

</div>
    {% endblock content %}

templates/sidebar.html
{% load mptt_tags %}
{% load static %}
  <ul class="menu bg-base-200 rounded-box m-5">
    <li>
      <h2 style="font-size: 18px;" class="menu-title text-center">Suv xo'jaligi faoliyati to'g'risida</h2>
  {% for category in sidebar_categories %}

        <li style="font-size: 18px;" class="mb-4">
          <a href="{% url 'app:post' category.article_id %}">
            <img src="{{ category.icon.url }}" class="h-6 w-6" fill="none" viewBox="0 0 60 60" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" /></svg>
            {{ category.name }}
          </a>
        </li>
  {% endfor %}


      </li>
  </ul>